// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The automated backup config for an instance.
public struct AutomatedBackupConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The automated backup mode. If the mode is disabled, the other
  /// fields will be ignored.
  public var automatedBackupMode: AutomatedBackupConfig.AutomatedBackupMode =
    AutomatedBackupConfig.AutomatedBackupMode()

  /// Optional. How long to keep automated backups before the backups are
  /// deleted. The value should be between 1 day and 365 days. If not specified,
  /// the default value is 35 days.
  public var retention: GoogleWKT.WKTDuration? = nil

  /// The schedule of automated backups.
  public var schedule: ScheduleOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AutomatedBackupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomatedBackupConfig().with { $0.fixedFrequencySchedule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fixedFrequencySchedule = CodingKeys(stringValue: "fixedFrequencySchedule")
    static let automatedBackupMode = CodingKeys(stringValue: "automatedBackupMode")
    static let retention = CodingKeys(stringValue: "retention")

    static let _knownKeys: Set<Swift.String> = [
      "fixedFrequencySchedule",
      "automatedBackupMode",
      "retention",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      AutomatedBackupConfig.AutomatedBackupMode.self, forKey: .automatedBackupMode)
    {
      self.automatedBackupMode = value
    }
    self.retention = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .retention)

    var schedule: ScheduleOneOf? = nil
    let scheduleCheckAndSet = {
      if schedule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'schedule'"))
      }
      schedule = $0
    }
    if let fixedFrequencySchedule = try container.decodeIfPresent(
      AutomatedBackupConfig.FixedFrequencySchedule?.self, forKey: .fixedFrequencySchedule)
    {
      try scheduleCheckAndSet(.fixedFrequencySchedule(fixedFrequencySchedule))
    }
    self.schedule = schedule
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.automatedBackupMode, forKey: .automatedBackupMode)
    try container.encodeIfPresent(self.retention, forKey: .retention)

    if let choice = self.schedule {
      switch choice {
      case .fixedFrequencySchedule(let value):
        try container.encode(value, forKey: .fixedFrequencySchedule)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// This schedule allows the backup to be triggered at a fixed frequency
  /// (currently only daily is supported).
  public struct FixedFrequencySchedule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The start time of every automated backup in UTC. It must be set
    /// to the start of an hour. This field is required.
    public var startTime: GoogleType.TimeOfDay? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FixedFrequencySchedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FixedFrequencySchedule().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startTime = CodingKeys(stringValue: "startTime")

      static let _knownKeys: Set<Swift.String> = [
        "startTime"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startTime = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .startTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.memorystore.v1.AutomatedBackupConfig.FixedFrequencySchedule"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The automated backup mode.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AutomatedBackupMode: Codable, Equatable, Hashable, Sendable {
    /// Default value. Automated backup config is not specified.
    case unspecified
    /// Automated backup config disabled.
    case disabled
    /// Automated backup config enabled.
    case enabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .disabled: return 1
      case .enabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUTOMATED_BACKUP_MODE_UNSPECIFIED"
      case .disabled: return "DISABLED"
      case .enabled: return "ENABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AutomatedBackupMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUTOMATED_BACKUP_MODE_UNSPECIFIED": self = .unspecified
      case "DISABLED": self = .disabled
      case "ENABLED": self = .enabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AutomatedBackupMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .disabled
      case 2: self = .enabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AUTOMATED_BACKUP_MODE_UNSPECIFIED")
      case .disabled: return try container.encode("DISABLED")
      case .enabled: return try container.encode("ENABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The schedule of automated backups.
  public enum ScheduleOneOf: Codable, Equatable, Sendable {
    /// Optional. Trigger automated backups at a fixed frequency.
    indirect case fixedFrequencySchedule(AutomatedBackupConfig.FixedFrequencySchedule?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.AutomatedBackupConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
