// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Backup of an instance.
public struct Backup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Full resource path of the backup. the last part of the name is
  /// the backup id with the following format: [YYYYMMDDHHMMSS]_[Shorted Instance
  /// UID] OR customer specified while backup instance. Example:
  /// 20240515123000_1234
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the backup was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Instance resource path of this backup.
  public var instance: Swift.String = Swift.String()

  /// Output only. Instance uid of this backup.
  public var instanceUid: Swift.String = Swift.String()

  /// Output only. Total size of the backup in bytes.
  public var totalSizeBytes: Swift.Int64 = Swift.Int64()

  /// Output only. The time when the backup will expire.
  public var expireTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. valkey-7.5/valkey-8.0, etc.
  public var engineVersion: Swift.String = Swift.String()

  /// Output only. List of backup files of the backup.
  public var backupFiles: [BackupFile] = []

  /// Output only. Node type of the instance.
  public var nodeType: Instance.NodeType = Instance.NodeType()

  /// Output only. Number of replicas for the instance.
  public var replicaCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of shards for the instance.
  public var shardCount: Swift.Int32 = Swift.Int32()

  /// Output only. Type of the backup.
  public var backupType: Backup.BackupType = Backup.BackupType()

  /// Output only. State of the backup.
  public var state: Backup.State = Backup.State()

  /// Output only. Encryption information of the backup.
  public var encryptionInfo: EncryptionInfo? = nil

  /// Output only. System assigned unique identifier of the backup.
  public var uid: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let instance = CodingKeys(stringValue: "instance")
    static let instanceUid = CodingKeys(stringValue: "instanceUid")
    static let totalSizeBytes = CodingKeys(stringValue: "totalSizeBytes")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let engineVersion = CodingKeys(stringValue: "engineVersion")
    static let backupFiles = CodingKeys(stringValue: "backupFiles")
    static let nodeType = CodingKeys(stringValue: "nodeType")
    static let replicaCount = CodingKeys(stringValue: "replicaCount")
    static let shardCount = CodingKeys(stringValue: "shardCount")
    static let backupType = CodingKeys(stringValue: "backupType")
    static let state = CodingKeys(stringValue: "state")
    static let encryptionInfo = CodingKeys(stringValue: "encryptionInfo")
    static let uid = CodingKeys(stringValue: "uid")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "instance",
      "instanceUid",
      "totalSizeBytes",
      "expireTime",
      "engineVersion",
      "backupFiles",
      "nodeType",
      "replicaCount",
      "shardCount",
      "backupType",
      "state",
      "encryptionInfo",
      "uid",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instance) {
      self.instance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceUid) {
      self.instanceUid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalSizeBytes) {
      self.totalSizeBytes = value
    }
    self.expireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .engineVersion) {
      self.engineVersion = value
    }
    if let value = try container.decodeIfPresent([BackupFile].self, forKey: .backupFiles) {
      self.backupFiles = value
    }
    if let value = try container.decodeIfPresent(Instance.NodeType.self, forKey: .nodeType) {
      self.nodeType = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .replicaCount) {
      self.replicaCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .shardCount) {
      self.shardCount = value
    }
    if let value = try container.decodeIfPresent(Backup.BackupType.self, forKey: .backupType) {
      self.backupType = value
    }
    if let value = try container.decodeIfPresent(Backup.State.self, forKey: .state) {
      self.state = value
    }
    self.encryptionInfo = try container.decodeIfPresent(
      EncryptionInfo.self, forKey: .encryptionInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.instance, forKey: .instance)
    try container.encode(self.instanceUid, forKey: .instanceUid)
    try container.encode(self.totalSizeBytes, forKey: .totalSizeBytes)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.engineVersion, forKey: .engineVersion)
    try container.encode(self.backupFiles, forKey: .backupFiles)
    try container.encode(self.nodeType, forKey: .nodeType)
    try container.encode(self.replicaCount, forKey: .replicaCount)
    try container.encode(self.shardCount, forKey: .shardCount)
    try container.encode(self.backupType, forKey: .backupType)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.encryptionInfo, forKey: .encryptionInfo)
    try container.encode(self.uid, forKey: .uid)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of the backup.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum BackupType: Codable, Equatable, Sendable {
    /// The default value, not set.
    case unspecified
    /// On-demand backup.
    case onDemand
    /// Automated backup.
    case automated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .onDemand: return 1
      case .automated: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKUP_TYPE_UNSPECIFIED"
      case .onDemand: return "ON_DEMAND"
      case .automated: return "AUTOMATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackupType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKUP_TYPE_UNSPECIFIED": self = .unspecified
      case "ON_DEMAND": self = .onDemand
      case "AUTOMATED": self = .automated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackupType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .onDemand
      case 2: self = .automated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BACKUP_TYPE_UNSPECIFIED")
      case .onDemand: return try container.encode("ON_DEMAND")
      case .automated: return try container.encode("AUTOMATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// State of the backup.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The default value, not set.
    case unspecified
    /// The backup is being created.
    case creating
    /// The backup is active to be used.
    case active
    /// The backup is being deleted.
    case deleting
    /// The backup is currently suspended due to reasons like project deletion,
    /// billing account closure, etc.
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .suspended: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .deleting: return try container.encode("DELETING")
      case .suspended: return try container.encode("SUSPENDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.Backup"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
