// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// BackupCollection of an instance.
public struct BackupCollection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Full resource path of the backup collection.
  public var name: Swift.String = Swift.String()

  /// Output only. The instance uid of the backup collection.
  public var instanceUid: Swift.String = Swift.String()

  /// Output only. The full resource path of the instance the backup collection
  /// belongs to. Example:
  /// projects/{project}/locations/{location}/instances/{instance}
  public var instance: Swift.String = Swift.String()

  /// Output only. The KMS key used to encrypt the backups under this backup
  /// collection.
  public var kmsKey: Swift.String = Swift.String()

  /// Output only. System assigned unique identifier of the backup collection.
  public var uid: Swift.String = Swift.String()

  /// Output only. The time when the backup collection was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Total size of all backups in the backup collection.
  public var totalBackupSizeBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Total number of backups in the backup collection.
  public var totalBackupCount: Swift.Int64 = Swift.Int64()

  /// Output only. The last time a backup was created in the backup collection.
  public var lastBackupTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupCollection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupCollection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let instanceUid = CodingKeys(stringValue: "instanceUid")
    static let instance = CodingKeys(stringValue: "instance")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let totalBackupSizeBytes = CodingKeys(stringValue: "totalBackupSizeBytes")
    static let totalBackupCount = CodingKeys(stringValue: "totalBackupCount")
    static let lastBackupTime = CodingKeys(stringValue: "lastBackupTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "instanceUid",
      "instance",
      "kmsKey",
      "uid",
      "createTime",
      "totalBackupSizeBytes",
      "totalBackupCount",
      "lastBackupTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceUid) {
      self.instanceUid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instance) {
      self.instance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBackupSizeBytes) {
      self.totalBackupSizeBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBackupCount) {
      self.totalBackupCount = value
    }
    self.lastBackupTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastBackupTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.instanceUid, forKey: .instanceUid)
    try container.encode(self.instance, forKey: .instance)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.totalBackupSizeBytes, forKey: .totalBackupSizeBytes)
    try container.encode(self.totalBackupCount, forKey: .totalBackupCount)
    try container.encodeIfPresent(self.lastBackupTime, forKey: .lastBackupTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.BackupCollection"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
