// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Cross instance replication config.
public struct CrossInstanceReplicationConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The role of the instance in cross instance replication.
  public var instanceRole: CrossInstanceReplicationConfig.InstanceRole =
    CrossInstanceReplicationConfig.InstanceRole()

  /// Optional. Details of the primary instance that is used as the replication
  /// source for this secondary instance.
  ///
  /// This field is only set for a secondary instance.
  public var primaryInstance: CrossInstanceReplicationConfig.RemoteInstance? = nil

  /// Optional. List of secondary instances that are replicating from this
  /// primary instance.
  ///
  /// This field is only set for a primary instance.
  public var secondaryInstances: [CrossInstanceReplicationConfig.RemoteInstance] = []

  /// Output only. The last time cross instance replication config was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. An output only view of all the member instances participating
  /// in the cross instance replication. This view will be provided by every
  /// member instance irrespective of its instance role(primary or secondary).
  ///
  /// A primary instance can provide information about all the secondary
  /// instances replicating from it. However, a secondary instance only knows
  /// about the primary instance from which it is replicating. However, for
  /// scenarios, where the primary instance is unavailable(e.g. regional outage),
  /// a Getinstance request can be sent to any other member instance and this
  /// field will list all the member instances participating in cross instance
  /// replication.
  public var membership: CrossInstanceReplicationConfig.Membership? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CrossInstanceReplicationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CrossInstanceReplicationConfig().with { $0.instanceRole = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let instanceRole = CodingKeys(stringValue: "instanceRole")
    static let primaryInstance = CodingKeys(stringValue: "primaryInstance")
    static let secondaryInstances = CodingKeys(stringValue: "secondaryInstances")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let membership = CodingKeys(stringValue: "membership")

    static let _knownKeys: Set<Swift.String> = [
      "instanceRole",
      "primaryInstance",
      "secondaryInstances",
      "updateTime",
      "membership",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      CrossInstanceReplicationConfig.InstanceRole.self, forKey: .instanceRole)
    {
      self.instanceRole = value
    }
    self.primaryInstance = try container.decodeIfPresent(
      CrossInstanceReplicationConfig.RemoteInstance.self, forKey: .primaryInstance)
    if let value = try container.decodeIfPresent(
      [CrossInstanceReplicationConfig.RemoteInstance].self, forKey: .secondaryInstances)
    {
      self.secondaryInstances = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.membership = try container.decodeIfPresent(
      CrossInstanceReplicationConfig.Membership.self, forKey: .membership)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.instanceRole, forKey: .instanceRole)
    try container.encodeIfPresent(self.primaryInstance, forKey: .primaryInstance)
    try container.encode(self.secondaryInstances, forKey: .secondaryInstances)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.membership, forKey: .membership)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details of the remote instance associated with this instance in a cross
  /// instance replication setup.
  public struct RemoteInstance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The full resource path of the remote instance in
    /// the format: projects/<project>/locations/<region>/instances/<instance-id>
    public var instance: Swift.String = Swift.String()

    /// Output only. The unique identifier of the remote instance.
    public var uid: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RemoteInstance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RemoteInstance().with { $0.instance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let instance = CodingKeys(stringValue: "instance")
      static let uid = CodingKeys(stringValue: "uid")

      static let _knownKeys: Set<Swift.String> = [
        "instance",
        "uid",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instance) {
        self.instance = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
        self.uid = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.instance, forKey: .instance)
      try container.encode(self.uid, forKey: .uid)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.memorystore.v1.CrossInstanceReplicationConfig.RemoteInstance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// An output only view of all the member instances participating in the cross
  /// instance replication.
  public struct Membership: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The primary instance that acts as the source of replication
    /// for the secondary instances.
    public var primaryInstance: CrossInstanceReplicationConfig.RemoteInstance? = nil

    /// Output only. The list of secondary instances replicating from the primary
    /// instance.
    public var secondaryInstances: [CrossInstanceReplicationConfig.RemoteInstance] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Membership`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Membership().with { $0.primaryInstance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let primaryInstance = CodingKeys(stringValue: "primaryInstance")
      static let secondaryInstances = CodingKeys(stringValue: "secondaryInstances")

      static let _knownKeys: Set<Swift.String> = [
        "primaryInstance",
        "secondaryInstances",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.primaryInstance = try container.decodeIfPresent(
        CrossInstanceReplicationConfig.RemoteInstance.self, forKey: .primaryInstance)
      if let value = try container.decodeIfPresent(
        [CrossInstanceReplicationConfig.RemoteInstance].self, forKey: .secondaryInstances)
      {
        self.secondaryInstances = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.primaryInstance, forKey: .primaryInstance)
      try container.encode(self.secondaryInstances, forKey: .secondaryInstances)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.memorystore.v1.CrossInstanceReplicationConfig.Membership"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The role of the instance in cross instance replication.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum InstanceRole: Codable, Equatable, Sendable {
    /// instance role is not set.
    /// The behavior is equivalent to NONE.
    case unspecified
    /// This instance does not participate in cross instance replication. It is
    /// an independent instance and does not replicate to or from any other
    /// instances.
    case `none`
    /// A instance that allows both reads and writes. Any data written to this
    /// instance is also replicated to the attached secondary instances.
    case primary
    /// A instance that allows only reads and replicates data from a primary
    /// instance.
    case secondary
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .primary: return 2
      case .secondary: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_ROLE_UNSPECIFIED"
      case .`none`: return "NONE"
      case .primary: return "PRIMARY"
      case .secondary: return "SECONDARY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstanceRole/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_ROLE_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "PRIMARY": self = .primary
      case "SECONDARY": self = .secondary
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstanceRole/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .primary
      case 3: self = .secondary
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INSTANCE_ROLE_UNSPECIFIED")
      case .`none`: return try container.encode("NONE")
      case .primary: return try container.encode("PRIMARY")
      case .secondary: return try container.encode("SECONDARY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.CrossInstanceReplicationConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
