// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// EncryptionInfo describes the encryption information of a cluster.
public struct EncryptionInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Type of encryption.
  public var encryptionType: EncryptionInfo.Type_ = EncryptionInfo.Type_()

  /// Output only. KMS key versions that are being used to protect the data
  /// at-rest.
  public var kmsKeyVersions: [Swift.String] = []

  /// Output only. The state of the primary version of the KMS key perceived by
  /// the system. This field is not populated in backups.
  public var kmsKeyPrimaryState: EncryptionInfo.KmsKeyState = EncryptionInfo.KmsKeyState()

  /// Output only. The most recent time when the encryption info was updated.
  public var lastUpdateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EncryptionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EncryptionInfo().with { $0.encryptionType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let encryptionType = CodingKeys(stringValue: "encryptionType")
    static let kmsKeyVersions = CodingKeys(stringValue: "kmsKeyVersions")
    static let kmsKeyPrimaryState = CodingKeys(stringValue: "kmsKeyPrimaryState")
    static let lastUpdateTime = CodingKeys(stringValue: "lastUpdateTime")

    static let _knownKeys: Set<Swift.String> = [
      "encryptionType",
      "kmsKeyVersions",
      "kmsKeyPrimaryState",
      "lastUpdateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(EncryptionInfo.Type_.self, forKey: .encryptionType)
    {
      self.encryptionType = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .kmsKeyVersions) {
      self.kmsKeyVersions = value
    }
    if let value = try container.decodeIfPresent(
      EncryptionInfo.KmsKeyState.self, forKey: .kmsKeyPrimaryState)
    {
      self.kmsKeyPrimaryState = value
    }
    self.lastUpdateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastUpdateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.encryptionType, forKey: .encryptionType)
    try container.encode(self.kmsKeyVersions, forKey: .kmsKeyVersions)
    try container.encode(self.kmsKeyPrimaryState, forKey: .kmsKeyPrimaryState)
    try container.encodeIfPresent(self.lastUpdateTime, forKey: .lastUpdateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible encryption types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// Encryption type not specified. Defaults to GOOGLE_DEFAULT_ENCRYPTION.
    case unspecified
    /// The data is encrypted at rest with a key that is fully managed by Google.
    /// No key version will be populated. This is the default state.
    case googleDefaultEncryption
    /// The data is encrypted at rest with a key that is managed by the customer.
    /// KMS key versions will be populated.
    case customerManagedEncryption
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .googleDefaultEncryption: return 1
      case .customerManagedEncryption: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .googleDefaultEncryption: return "GOOGLE_DEFAULT_ENCRYPTION"
      case .customerManagedEncryption: return "CUSTOMER_MANAGED_ENCRYPTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "GOOGLE_DEFAULT_ENCRYPTION": self = .googleDefaultEncryption
      case "CUSTOMER_MANAGED_ENCRYPTION": self = .customerManagedEncryption
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .googleDefaultEncryption
      case 2: self = .customerManagedEncryption
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .googleDefaultEncryption: return try container.encode("GOOGLE_DEFAULT_ENCRYPTION")
      case .customerManagedEncryption: return try container.encode("CUSTOMER_MANAGED_ENCRYPTION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The state of the KMS key perceived by the system. Refer to the public
  /// documentation for the impact of each state.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum KmsKeyState: Codable, Equatable, Hashable, Sendable {
    /// The default value. This value is unused.
    case unspecified
    /// The KMS key is enabled and correctly configured.
    case enabled
    /// Permission denied on the KMS key.
    case permissionDenied
    /// The KMS key is disabled.
    case disabled
    /// The KMS key is destroyed.
    case destroyed
    /// The KMS key is scheduled to be destroyed.
    case destroyScheduled
    /// The EKM key is unreachable.
    case ekmKeyUnreachableDetected
    /// Billing is disabled for the project.
    case billingDisabled
    /// All other unknown failures.
    case unknownFailure
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .permissionDenied: return 2
      case .disabled: return 3
      case .destroyed: return 4
      case .destroyScheduled: return 5
      case .ekmKeyUnreachableDetected: return 6
      case .billingDisabled: return 7
      case .unknownFailure: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "KMS_KEY_STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .disabled: return "DISABLED"
      case .destroyed: return "DESTROYED"
      case .destroyScheduled: return "DESTROY_SCHEDULED"
      case .ekmKeyUnreachableDetected: return "EKM_KEY_UNREACHABLE_DETECTED"
      case .billingDisabled: return "BILLING_DISABLED"
      case .unknownFailure: return "UNKNOWN_FAILURE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:KmsKeyState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "KMS_KEY_STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "PERMISSION_DENIED": self = .permissionDenied
      case "DISABLED": self = .disabled
      case "DESTROYED": self = .destroyed
      case "DESTROY_SCHEDULED": self = .destroyScheduled
      case "EKM_KEY_UNREACHABLE_DETECTED": self = .ekmKeyUnreachableDetected
      case "BILLING_DISABLED": self = .billingDisabled
      case "UNKNOWN_FAILURE": self = .unknownFailure
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:KmsKeyState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .permissionDenied
      case 3: self = .disabled
      case 4: self = .destroyed
      case 5: self = .destroyScheduled
      case 6: self = .ekmKeyUnreachableDetected
      case 7: self = .billingDisabled
      case 8: self = .unknownFailure
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("KMS_KEY_STATE_UNSPECIFIED")
      case .enabled: return try container.encode("ENABLED")
      case .permissionDenied: return try container.encode("PERMISSION_DENIED")
      case .disabled: return try container.encode("DISABLED")
      case .destroyed: return try container.encode("DESTROYED")
      case .destroyScheduled: return try container.encode("DESTROY_SCHEDULED")
      case .ekmKeyUnreachableDetected: return try container.encode("EKM_KEY_UNREACHABLE_DETECTED")
      case .billingDisabled: return try container.encode("BILLING_DISABLED")
      case .unknownFailure: return try container.encode("UNKNOWN_FAILURE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.EncryptionInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
