// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for `ExportBackup`.
public struct ExportBackupRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Instance backup resource name using the form:
  /// `projects/{project_id}/locations/{location_id}/backupCollections/{backup_collection_id}/backups/{backup_id}`
  public var name: Swift.String = Swift.String()

  /// Required. Specify destination to export a backup.
  public var destination: OneOf_Destination? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExportBackupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportBackupRequest().with { $0.gcsBucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsBucket = CodingKeys(stringValue: "gcsBucket")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "gcsBucket",
      "name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsBucket = try container.decodeIfPresent(Swift.String.self, forKey: .gcsBucket) {
      try destinationCheckAndSet(.gcsBucket(gcsBucket))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.destination {
      switch choice {
      case .gcsBucket(let value):
        try container.encode(value, forKey: .gcsBucket)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required. Specify destination to export a backup.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Google Cloud Storage bucket, like "my-bucket".
    case gcsBucket(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.ExportBackupRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
