// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Memorystore instance.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Unique name of the instance.
  /// Format: projects/{project}/locations/{location}/instances/{instance}
  public var name: Swift.String = Swift.String()

  /// Output only. Creation timestamp of the instance.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Latest update timestamp of the instance.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Labels to represent user-provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Current state of the instance.
  public var state: Instance.State = Instance.State()

  /// Output only. Additional information about the state of the instance.
  public var stateInfo: Instance.StateInfo? = nil

  /// Output only. System assigned, unique identifier for the instance.
  public var uid: Swift.String = Swift.String()

  /// Optional. Number of replica nodes per shard. If omitted the default is 0
  /// replicas.
  public var replicaCount: Swift.Int32? = nil

  /// Optional. Immutable. Authorization mode of the instance.
  public var authorizationMode: Instance.AuthorizationMode = Instance.AuthorizationMode()

  /// Optional. Immutable. In-transit encryption mode of the instance.
  public var transitEncryptionMode: Instance.TransitEncryptionMode =
    Instance.TransitEncryptionMode()

  /// Optional. Number of shards for the instance.
  public var shardCount: Swift.Int32 = Swift.Int32()

  /// Output only. Deprecated: The discovery_endpoints parameter is deprecated.
  /// As a result, it will not be populated if the connections are created using
  /// endpoints parameter. Instead of this parameter, for discovery, use
  /// endpoints.connections.pscConnection and
  /// endpoints.connections.pscAutoConnection
  /// with connectionType CONNECTION_TYPE_DISCOVERY.
  @available(*, deprecated)
  public var discoveryEndpoints: [DiscoveryEndpoint] = []

  /// Optional. Machine type for individual nodes of the instance.
  public var nodeType: Instance.NodeType = Instance.NodeType()

  /// Optional. Persistence configuration of the instance.
  public var persistenceConfig: PersistenceConfig? = nil

  /// Optional. Engine version of the instance.
  public var engineVersion: Swift.String = Swift.String()

  /// Optional. User-provided engine configurations for the instance.
  public var engineConfigs: [Swift.String: Swift.String] = [:]

  /// Output only. Configuration of individual nodes of the instance.
  public var nodeConfig: NodeConfig? = nil

  /// Optional. Immutable. Zone distribution configuration of the instance for
  /// node allocation.
  public var zoneDistributionConfig: ZoneDistributionConfig? = nil

  /// Optional. If set to true deletion of the instance will fail.
  public var deletionProtectionEnabled: Swift.Bool? = nil

  /// Optional. Immutable. Deprecated: Use the
  /// endpoints.connections.psc_auto_connection value instead.
  @available(*, deprecated)
  public var pscAutoConnections: [PscAutoConnection] = []

  /// Output only. Service attachment details to configure PSC connections.
  public var pscAttachmentDetails: [PscAttachmentDetail] = []

  /// Optional. Endpoints for the instance.
  public var endpoints: [Instance.InstanceEndpoint] = []

  /// Optional. Immutable. The mode config for the instance.
  public var mode: Instance.Mode = Instance.Mode()

  /// Optional. Input only. Simulate a maintenance event.
  public var simulateMaintenanceEvent: Swift.Bool? = nil

  /// Optional. Input only. Ondemand maintenance for the instance.
  @available(*, deprecated)
  public var ondemandMaintenance: Swift.Bool? = nil

  /// Optional. Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool? = nil

  /// Optional. Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool? = nil

  /// Optional. The maintenance policy for the instance. If not provided,
  /// the maintenance event will be performed based on Memorystore
  /// internal rollout schedule.
  public var maintenancePolicy: MaintenancePolicy? = nil

  /// Output only. Published maintenance schedule.
  public var maintenanceSchedule: MaintenanceSchedule? = nil

  /// Optional. The config for cross instance replication.
  public var crossInstanceReplicationConfig: CrossInstanceReplicationConfig? = nil

  /// Optional. If true, instance endpoints that are created and registered by
  /// customers can be deleted asynchronously. That is, such an instance endpoint
  /// can be de-registered before the forwarding rules in the instance endpoint
  /// are deleted.
  public var asyncInstanceEndpointsDeletionEnabled: Swift.Bool? = nil

  /// Optional. The KMS key used to encrypt the at-rest data of the cluster.
  public var kmsKey: Swift.String? = nil

  /// Output only. Encryption information of the data at rest of the cluster.
  public var encryptionInfo: EncryptionInfo? = nil

  /// Output only. The backup collection full resource name. Example:
  /// projects/{project}/locations/{location}/backupCollections/{collection}
  public var backupCollection: Swift.String? = nil

  /// Optional. The automated backup config for the instance.
  public var automatedBackupConfig: AutomatedBackupConfig? = nil

  /// Optional. This field can be used to trigger self service update to indicate
  /// the desired maintenance version. The input to this field can be determined
  /// by the available_maintenance_versions field.
  public var maintenanceVersion: Swift.String? = nil

  /// Output only. This field represents the actual maintenance version of the
  /// instance.
  public var effectiveMaintenanceVersion: Swift.String? = nil

  /// Output only. This field is used to determine the available maintenance
  /// versions for the self service update.
  public var availableMaintenanceVersions: [Swift.String] = []

  /// Optional. Immutable. Deprecated, do not use.
  @available(*, deprecated)
  public var allowFewerZonesDeployment: Swift.Bool = Swift.Bool()

  /// Optional. Immutable. The Server CA mode for the instance.
  public var serverCaMode: Instance.ServerCaMode? = nil

  /// Optional. Immutable. The customer-managed CA pool for the instance. Only
  /// applicable if the Server CA mode is CUSTOMER_MANAGED_CAS_CA. Format:
  /// "projects/{project}/locations/{region}/caPools/{ca_pool}".
  public var serverCaPool: Swift.String? = nil

  /// Optional. Input only. Rotate the server certificates.
  public var rotateServerCertificate: Swift.Bool? = nil

  /// Output only. Migration config for the instance.
  public var migrationConfig: MigrationConfig? = nil

  /// The source to import from.
  public var importSources: OneOf_ImportSources? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.gcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsSource = CodingKeys(stringValue: "gcsSource")
    static let managedBackupSource = CodingKeys(stringValue: "managedBackupSource")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let stateInfo = CodingKeys(stringValue: "stateInfo")
    static let uid = CodingKeys(stringValue: "uid")
    static let replicaCount = CodingKeys(stringValue: "replicaCount")
    static let authorizationMode = CodingKeys(stringValue: "authorizationMode")
    static let transitEncryptionMode = CodingKeys(stringValue: "transitEncryptionMode")
    static let shardCount = CodingKeys(stringValue: "shardCount")
    static let discoveryEndpoints = CodingKeys(stringValue: "discoveryEndpoints")
    static let nodeType = CodingKeys(stringValue: "nodeType")
    static let persistenceConfig = CodingKeys(stringValue: "persistenceConfig")
    static let engineVersion = CodingKeys(stringValue: "engineVersion")
    static let engineConfigs = CodingKeys(stringValue: "engineConfigs")
    static let nodeConfig = CodingKeys(stringValue: "nodeConfig")
    static let zoneDistributionConfig = CodingKeys(stringValue: "zoneDistributionConfig")
    static let deletionProtectionEnabled = CodingKeys(stringValue: "deletionProtectionEnabled")
    static let pscAutoConnections = CodingKeys(stringValue: "pscAutoConnections")
    static let pscAttachmentDetails = CodingKeys(stringValue: "pscAttachmentDetails")
    static let endpoints = CodingKeys(stringValue: "endpoints")
    static let mode = CodingKeys(stringValue: "mode")
    static let simulateMaintenanceEvent = CodingKeys(stringValue: "simulateMaintenanceEvent")
    static let ondemandMaintenance = CodingKeys(stringValue: "ondemandMaintenance")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")
    static let maintenancePolicy = CodingKeys(stringValue: "maintenancePolicy")
    static let maintenanceSchedule = CodingKeys(stringValue: "maintenanceSchedule")
    static let crossInstanceReplicationConfig = CodingKeys(
      stringValue: "crossInstanceReplicationConfig")
    static let asyncInstanceEndpointsDeletionEnabled = CodingKeys(
      stringValue: "asyncInstanceEndpointsDeletionEnabled")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let encryptionInfo = CodingKeys(stringValue: "encryptionInfo")
    static let backupCollection = CodingKeys(stringValue: "backupCollection")
    static let automatedBackupConfig = CodingKeys(stringValue: "automatedBackupConfig")
    static let maintenanceVersion = CodingKeys(stringValue: "maintenanceVersion")
    static let effectiveMaintenanceVersion = CodingKeys(stringValue: "effectiveMaintenanceVersion")
    static let availableMaintenanceVersions = CodingKeys(
      stringValue: "availableMaintenanceVersions")
    static let allowFewerZonesDeployment = CodingKeys(stringValue: "allowFewerZonesDeployment")
    static let serverCaMode = CodingKeys(stringValue: "serverCaMode")
    static let serverCaPool = CodingKeys(stringValue: "serverCaPool")
    static let rotateServerCertificate = CodingKeys(stringValue: "rotateServerCertificate")
    static let migrationConfig = CodingKeys(stringValue: "migrationConfig")

    static let _knownKeys: Set<Swift.String> = [
      "gcsSource",
      "managedBackupSource",
      "name",
      "createTime",
      "updateTime",
      "labels",
      "state",
      "stateInfo",
      "uid",
      "replicaCount",
      "authorizationMode",
      "transitEncryptionMode",
      "shardCount",
      "discoveryEndpoints",
      "nodeType",
      "persistenceConfig",
      "engineVersion",
      "engineConfigs",
      "nodeConfig",
      "zoneDistributionConfig",
      "deletionProtectionEnabled",
      "pscAutoConnections",
      "pscAttachmentDetails",
      "endpoints",
      "mode",
      "simulateMaintenanceEvent",
      "ondemandMaintenance",
      "satisfiesPzs",
      "satisfiesPzi",
      "maintenancePolicy",
      "maintenanceSchedule",
      "crossInstanceReplicationConfig",
      "asyncInstanceEndpointsDeletionEnabled",
      "kmsKey",
      "encryptionInfo",
      "backupCollection",
      "automatedBackupConfig",
      "maintenanceVersion",
      "effectiveMaintenanceVersion",
      "availableMaintenanceVersions",
      "allowFewerZonesDeployment",
      "serverCaMode",
      "serverCaPool",
      "rotateServerCertificate",
      "migrationConfig",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    self.stateInfo = try container.decodeIfPresent(Instance.StateInfo.self, forKey: .stateInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.replicaCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .replicaCount)
    if let value = try container.decodeIfPresent(
      Instance.AuthorizationMode.self, forKey: .authorizationMode)
    {
      self.authorizationMode = value
    }
    if let value = try container.decodeIfPresent(
      Instance.TransitEncryptionMode.self, forKey: .transitEncryptionMode)
    {
      self.transitEncryptionMode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .shardCount) {
      self.shardCount = value
    }
    if let value = try container.decodeIfPresent(
      [DiscoveryEndpoint].self, forKey: .discoveryEndpoints)
    {
      self.discoveryEndpoints = value
    }
    if let value = try container.decodeIfPresent(Instance.NodeType.self, forKey: .nodeType) {
      self.nodeType = value
    }
    self.persistenceConfig = try container.decodeIfPresent(
      PersistenceConfig.self, forKey: .persistenceConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .engineVersion) {
      self.engineVersion = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .engineConfigs)
    {
      self.engineConfigs = value
    }
    self.nodeConfig = try container.decodeIfPresent(NodeConfig.self, forKey: .nodeConfig)
    self.zoneDistributionConfig = try container.decodeIfPresent(
      ZoneDistributionConfig.self, forKey: .zoneDistributionConfig)
    self.deletionProtectionEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .deletionProtectionEnabled)
    if let value = try container.decodeIfPresent(
      [PscAutoConnection].self, forKey: .pscAutoConnections)
    {
      self.pscAutoConnections = value
    }
    if let value = try container.decodeIfPresent(
      [PscAttachmentDetail].self, forKey: .pscAttachmentDetails)
    {
      self.pscAttachmentDetails = value
    }
    if let value = try container.decodeIfPresent(
      [Instance.InstanceEndpoint].self, forKey: .endpoints)
    {
      self.endpoints = value
    }
    if let value = try container.decodeIfPresent(Instance.Mode.self, forKey: .mode) {
      self.mode = value
    }
    self.simulateMaintenanceEvent = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .simulateMaintenanceEvent)
    self.ondemandMaintenance = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .ondemandMaintenance)
    self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
    self.satisfiesPzi = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi)
    self.maintenancePolicy = try container.decodeIfPresent(
      MaintenancePolicy.self, forKey: .maintenancePolicy)
    self.maintenanceSchedule = try container.decodeIfPresent(
      MaintenanceSchedule.self, forKey: .maintenanceSchedule)
    self.crossInstanceReplicationConfig = try container.decodeIfPresent(
      CrossInstanceReplicationConfig.self, forKey: .crossInstanceReplicationConfig)
    self.asyncInstanceEndpointsDeletionEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .asyncInstanceEndpointsDeletionEnabled)
    self.kmsKey = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey)
    self.encryptionInfo = try container.decodeIfPresent(
      EncryptionInfo.self, forKey: .encryptionInfo)
    self.backupCollection = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupCollection)
    self.automatedBackupConfig = try container.decodeIfPresent(
      AutomatedBackupConfig.self, forKey: .automatedBackupConfig)
    self.maintenanceVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .maintenanceVersion)
    self.effectiveMaintenanceVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .effectiveMaintenanceVersion)
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .availableMaintenanceVersions)
    {
      self.availableMaintenanceVersions = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .allowFewerZonesDeployment)
    {
      self.allowFewerZonesDeployment = value
    }
    self.serverCaMode = try container.decodeIfPresent(
      Instance.ServerCaMode.self, forKey: .serverCaMode)
    self.serverCaPool = try container.decodeIfPresent(Swift.String.self, forKey: .serverCaPool)
    self.rotateServerCertificate = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .rotateServerCertificate)
    self.migrationConfig = try container.decodeIfPresent(
      MigrationConfig.self, forKey: .migrationConfig)

    var importSources: OneOf_ImportSources? = nil
    let importSourcesCheckAndSet = {
      if importSources != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'importSources'"))
      }
      importSources = $0
    }
    if let gcsSource = try container.decodeIfPresent(
      Instance.GcsBackupSource?.self, forKey: .gcsSource)
    {
      try importSourcesCheckAndSet(.gcsSource(gcsSource))
    }
    if let managedBackupSource = try container.decodeIfPresent(
      Instance.ManagedBackupSource?.self, forKey: .managedBackupSource)
    {
      try importSourcesCheckAndSet(.managedBackupSource(managedBackupSource))
    }
    self.importSources = importSources
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.stateInfo, forKey: .stateInfo)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.replicaCount, forKey: .replicaCount)
    try container.encode(self.authorizationMode, forKey: .authorizationMode)
    try container.encode(self.transitEncryptionMode, forKey: .transitEncryptionMode)
    try container.encode(self.shardCount, forKey: .shardCount)
    try container.encode(self.discoveryEndpoints, forKey: .discoveryEndpoints)
    try container.encode(self.nodeType, forKey: .nodeType)
    try container.encodeIfPresent(self.persistenceConfig, forKey: .persistenceConfig)
    try container.encode(self.engineVersion, forKey: .engineVersion)
    try container.encode(self.engineConfigs, forKey: .engineConfigs)
    try container.encodeIfPresent(self.nodeConfig, forKey: .nodeConfig)
    try container.encodeIfPresent(self.zoneDistributionConfig, forKey: .zoneDistributionConfig)
    try container.encodeIfPresent(
      self.deletionProtectionEnabled, forKey: .deletionProtectionEnabled)
    try container.encode(self.pscAutoConnections, forKey: .pscAutoConnections)
    try container.encode(self.pscAttachmentDetails, forKey: .pscAttachmentDetails)
    try container.encode(self.endpoints, forKey: .endpoints)
    try container.encode(self.mode, forKey: .mode)
    try container.encodeIfPresent(self.simulateMaintenanceEvent, forKey: .simulateMaintenanceEvent)
    try container.encodeIfPresent(self.ondemandMaintenance, forKey: .ondemandMaintenance)
    try container.encodeIfPresent(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encodeIfPresent(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encodeIfPresent(self.maintenancePolicy, forKey: .maintenancePolicy)
    try container.encodeIfPresent(self.maintenanceSchedule, forKey: .maintenanceSchedule)
    try container.encodeIfPresent(
      self.crossInstanceReplicationConfig, forKey: .crossInstanceReplicationConfig)
    try container.encodeIfPresent(
      self.asyncInstanceEndpointsDeletionEnabled, forKey: .asyncInstanceEndpointsDeletionEnabled)
    try container.encodeIfPresent(self.kmsKey, forKey: .kmsKey)
    try container.encodeIfPresent(self.encryptionInfo, forKey: .encryptionInfo)
    try container.encodeIfPresent(self.backupCollection, forKey: .backupCollection)
    try container.encodeIfPresent(self.automatedBackupConfig, forKey: .automatedBackupConfig)
    try container.encodeIfPresent(self.maintenanceVersion, forKey: .maintenanceVersion)
    try container.encodeIfPresent(
      self.effectiveMaintenanceVersion, forKey: .effectiveMaintenanceVersion)
    try container.encode(self.availableMaintenanceVersions, forKey: .availableMaintenanceVersions)
    try container.encode(self.allowFewerZonesDeployment, forKey: .allowFewerZonesDeployment)
    try container.encodeIfPresent(self.serverCaMode, forKey: .serverCaMode)
    try container.encodeIfPresent(self.serverCaPool, forKey: .serverCaPool)
    try container.encodeIfPresent(self.rotateServerCertificate, forKey: .rotateServerCertificate)
    try container.encodeIfPresent(self.migrationConfig, forKey: .migrationConfig)

    if let choice = self.importSources {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      case .managedBackupSource(let value):
        try container.encode(value, forKey: .managedBackupSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Additional information about the state of the instance.
  public struct StateInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var info: OneOf_Info? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StateInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StateInfo().with { $0.updateInfo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let updateInfo = CodingKeys(stringValue: "updateInfo")

      static let _knownKeys: Set<Swift.String> = [
        "updateInfo"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var info: OneOf_Info? = nil
      let infoCheckAndSet = {
        if info != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'info'"))
        }
        info = $0
      }
      if let updateInfo = try container.decodeIfPresent(
        Instance.StateInfo.UpdateInfo?.self, forKey: .updateInfo)
      {
        try infoCheckAndSet(.updateInfo(updateInfo))
      }
      self.info = info
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.info {
        switch choice {
        case .updateInfo(let value):
          try container.encode(value, forKey: .updateInfo)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Represents information about instance with state UPDATING.
    public struct UpdateInfo: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. Target number of shards for the instance.
      public var targetShardCount: Swift.Int32? = nil

      /// Output only. Target number of replica nodes per shard for the instance.
      public var targetReplicaCount: Swift.Int32? = nil

      /// Output only. Target engine version for the instance.
      public var targetEngineVersion: Swift.String? = nil

      /// Output only. Target node type for the instance.
      public var targetNodeType: Instance.NodeType? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `UpdateInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = UpdateInfo().with { $0.targetShardCount = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let targetShardCount = CodingKeys(stringValue: "targetShardCount")
        static let targetReplicaCount = CodingKeys(stringValue: "targetReplicaCount")
        static let targetEngineVersion = CodingKeys(stringValue: "targetEngineVersion")
        static let targetNodeType = CodingKeys(stringValue: "targetNodeType")

        static let _knownKeys: Set<Swift.String> = [
          "targetShardCount",
          "targetReplicaCount",
          "targetEngineVersion",
          "targetNodeType",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.targetShardCount = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .targetShardCount)
        self.targetReplicaCount = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .targetReplicaCount)
        self.targetEngineVersion = try container.decodeIfPresent(
          Swift.String.self, forKey: .targetEngineVersion)
        self.targetNodeType = try container.decodeIfPresent(
          Instance.NodeType.self, forKey: .targetNodeType)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.targetShardCount, forKey: .targetShardCount)
        try container.encodeIfPresent(self.targetReplicaCount, forKey: .targetReplicaCount)
        try container.encodeIfPresent(self.targetEngineVersion, forKey: .targetEngineVersion)
        try container.encodeIfPresent(self.targetNodeType, forKey: .targetNodeType)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.memorystore.v1.Instance.StateInfo.UpdateInfo"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_Info: Codable, Equatable, Sendable {
      /// Output only. Describes ongoing update when instance state is UPDATING.
      indirect case updateInfo(Instance.StateInfo.UpdateInfo?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.Instance.StateInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Backups that stored in Cloud Storage buckets.
  /// The Cloud Storage buckets need to be the same region as the instances.
  public struct GcsBackupSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Example: gs://bucket1/object1, gs://bucket2/folder2/object2
    public var uris: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GcsBackupSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcsBackupSource().with { $0.uris = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uris = CodingKeys(stringValue: "uris")

      static let _knownKeys: Set<Swift.String> = [
        "uris"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .uris) {
        self.uris = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uris, forKey: .uris)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.Instance.GcsBackupSource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Backups that generated and managed by memorystore.
  public struct ManagedBackupSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Example:
    /// //memorystore.googleapis.com/projects/{project}/locations/{location}/backupCollections/{collection}/backups/{backup}
    /// A shorter version (without the prefix) of the backup name is also
    /// supported, like
    /// projects/{project}/locations/{location}/backupCollections/{collection}/backups/{backup_id}
    /// In this case, it assumes the backup is under memorystore.googleapis.com.
    public var backup: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ManagedBackupSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ManagedBackupSource().with { $0.backup = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let backup = CodingKeys(stringValue: "backup")

      static let _knownKeys: Set<Swift.String> = [
        "backup"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backup) {
        self.backup = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.backup, forKey: .backup)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.Instance.ManagedBackupSource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// InstanceEndpoint consists of PSC connections that are created
  /// as a group in each VPC network for accessing the instance. In each group,
  /// there shall be one connection for each service attachment in the cluster.
  public struct InstanceEndpoint: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A group of PSC connections. They are created in the same VPC
    /// network, one for each service attachment in the cluster.
    public var connections: [Instance.ConnectionDetail] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceEndpoint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceEndpoint().with { $0.connections = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let connections = CodingKeys(stringValue: "connections")

      static let _knownKeys: Set<Swift.String> = [
        "connections"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Instance.ConnectionDetail].self, forKey: .connections)
      {
        self.connections = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.connections, forKey: .connections)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.Instance.InstanceEndpoint"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information of each PSC connection.
  public struct ConnectionDetail: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A PSC connection to an instance could either be created through Service
    /// Connectivity Automation (auto connection) during the cluster creation,
    /// or it could be created by customer themeslves (user-created connection).
    public var connection: OneOf_Connection? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConnectionDetail`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectionDetail().with { $0.pscAutoConnection = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pscAutoConnection = CodingKeys(stringValue: "pscAutoConnection")
      static let pscConnection = CodingKeys(stringValue: "pscConnection")

      static let _knownKeys: Set<Swift.String> = [
        "pscAutoConnection",
        "pscConnection",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var connection: OneOf_Connection? = nil
      let connectionCheckAndSet = {
        if connection != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'connection'"))
        }
        connection = $0
      }
      if let pscAutoConnection = try container.decodeIfPresent(
        PscAutoConnection?.self, forKey: .pscAutoConnection)
      {
        try connectionCheckAndSet(.pscAutoConnection(pscAutoConnection))
      }
      if let pscConnection = try container.decodeIfPresent(
        PscConnection?.self, forKey: .pscConnection)
      {
        try connectionCheckAndSet(.pscConnection(pscConnection))
      }
      self.connection = connection
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.connection {
        switch choice {
        case .pscAutoConnection(let value):
          try container.encode(value, forKey: .pscAutoConnection)
        case .pscConnection(let value):
          try container.encode(value, forKey: .pscConnection)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A PSC connection to an instance could either be created through Service
    /// Connectivity Automation (auto connection) during the cluster creation,
    /// or it could be created by customer themeslves (user-created connection).
    public enum OneOf_Connection: Codable, Equatable, Sendable {
      /// Immutable. Detailed information of a PSC connection that is created
      /// through service connectivity automation.
      indirect case pscAutoConnection(PscAutoConnection?)
      /// Detailed information of a PSC connection that is created by the user.
      indirect case pscConnection(PscConnection?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.Instance.ConnectionDetail"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible states of the instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Instance is being created.
    case creating
    /// Instance has been created and is usable.
    case active
    /// Instance is being updated.
    case updating
    /// Instance is being deleted.
    case deleting
    /// Instance is being migrated.
    case migrating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .migrating: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .migrating: return "MIGRATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "MIGRATING": self = .migrating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      case 6: self = .migrating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .migrating: return try container.encode("MIGRATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible authorization modes of the instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AuthorizationMode: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Authorization disabled.
    case authDisabled
    /// IAM basic authorization.
    case iamAuth
    /// Token based authorization.
    case tokenAuth
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .authDisabled: return 1
      case .iamAuth: return 2
      case .tokenAuth: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUTHORIZATION_MODE_UNSPECIFIED"
      case .authDisabled: return "AUTH_DISABLED"
      case .iamAuth: return "IAM_AUTH"
      case .tokenAuth: return "TOKEN_AUTH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuthorizationMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUTHORIZATION_MODE_UNSPECIFIED": self = .unspecified
      case "AUTH_DISABLED": self = .authDisabled
      case "IAM_AUTH": self = .iamAuth
      case "TOKEN_AUTH": self = .tokenAuth
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuthorizationMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .authDisabled
      case 2: self = .iamAuth
      case 3: self = .tokenAuth
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AUTHORIZATION_MODE_UNSPECIFIED")
      case .authDisabled: return try container.encode("AUTH_DISABLED")
      case .iamAuth: return try container.encode("IAM_AUTH")
      case .tokenAuth: return try container.encode("TOKEN_AUTH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible in-transit encryption modes of the instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum TransitEncryptionMode: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// In-transit encryption is disabled.
    case transitEncryptionDisabled
    /// Server-managed encryption is used for in-transit encryption.
    case serverAuthentication
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .transitEncryptionDisabled: return 1
      case .serverAuthentication: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRANSIT_ENCRYPTION_MODE_UNSPECIFIED"
      case .transitEncryptionDisabled: return "TRANSIT_ENCRYPTION_DISABLED"
      case .serverAuthentication: return "SERVER_AUTHENTICATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TransitEncryptionMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRANSIT_ENCRYPTION_MODE_UNSPECIFIED": self = .unspecified
      case "TRANSIT_ENCRYPTION_DISABLED": self = .transitEncryptionDisabled
      case "SERVER_AUTHENTICATION": self = .serverAuthentication
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TransitEncryptionMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .transitEncryptionDisabled
      case 2: self = .serverAuthentication
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TRANSIT_ENCRYPTION_MODE_UNSPECIFIED")
      case .transitEncryptionDisabled: return try container.encode("TRANSIT_ENCRYPTION_DISABLED")
      case .serverAuthentication: return try container.encode("SERVER_AUTHENTICATION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible node types of the instance. See
  /// https://cloud.google.com/memorystore/docs/valkey/instance-node-specification
  /// for more information.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum NodeType: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Shared core nano.
    case sharedCoreNano
    /// High memory medium.
    case highmemMedium
    /// High memory extra large.
    case highmemXlarge
    /// Standard small.
    case standardSmall
    /// Custom micro.
    case customMicro
    /// Custom mini.
    case customMini
    /// High cpu medium.
    case highcpuMedium
    /// Standard large.
    case standardLarge
    /// High memory 2xlarge.
    case highmem2Xlarge
    /// Custom pico.
    case customPico
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .sharedCoreNano: return 1
      case .highmemMedium: return 2
      case .highmemXlarge: return 3
      case .standardSmall: return 4
      case .customMicro: return 5
      case .customMini: return 6
      case .highcpuMedium: return 7
      case .standardLarge: return 8
      case .highmem2Xlarge: return 9
      case .customPico: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NODE_TYPE_UNSPECIFIED"
      case .sharedCoreNano: return "SHARED_CORE_NANO"
      case .highmemMedium: return "HIGHMEM_MEDIUM"
      case .highmemXlarge: return "HIGHMEM_XLARGE"
      case .standardSmall: return "STANDARD_SMALL"
      case .customMicro: return "CUSTOM_MICRO"
      case .customMini: return "CUSTOM_MINI"
      case .highcpuMedium: return "HIGHCPU_MEDIUM"
      case .standardLarge: return "STANDARD_LARGE"
      case .highmem2Xlarge: return "HIGHMEM_2XLARGE"
      case .customPico: return "CUSTOM_PICO"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NodeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NODE_TYPE_UNSPECIFIED": self = .unspecified
      case "SHARED_CORE_NANO": self = .sharedCoreNano
      case "HIGHMEM_MEDIUM": self = .highmemMedium
      case "HIGHMEM_XLARGE": self = .highmemXlarge
      case "STANDARD_SMALL": self = .standardSmall
      case "CUSTOM_MICRO": self = .customMicro
      case "CUSTOM_MINI": self = .customMini
      case "HIGHCPU_MEDIUM": self = .highcpuMedium
      case "STANDARD_LARGE": self = .standardLarge
      case "HIGHMEM_2XLARGE": self = .highmem2Xlarge
      case "CUSTOM_PICO": self = .customPico
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NodeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .sharedCoreNano
      case 2: self = .highmemMedium
      case 3: self = .highmemXlarge
      case 4: self = .standardSmall
      case 5: self = .customMicro
      case 6: self = .customMini
      case 7: self = .highcpuMedium
      case 8: self = .standardLarge
      case 9: self = .highmem2Xlarge
      case 10: self = .customPico
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("NODE_TYPE_UNSPECIFIED")
      case .sharedCoreNano: return try container.encode("SHARED_CORE_NANO")
      case .highmemMedium: return try container.encode("HIGHMEM_MEDIUM")
      case .highmemXlarge: return try container.encode("HIGHMEM_XLARGE")
      case .standardSmall: return try container.encode("STANDARD_SMALL")
      case .customMicro: return try container.encode("CUSTOM_MICRO")
      case .customMini: return try container.encode("CUSTOM_MINI")
      case .highcpuMedium: return try container.encode("HIGHCPU_MEDIUM")
      case .standardLarge: return try container.encode("STANDARD_LARGE")
      case .highmem2Xlarge: return try container.encode("HIGHMEM_2XLARGE")
      case .customPico: return try container.encode("CUSTOM_PICO")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The mode config, which is used to enable/disable cluster mode.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Mode: Codable, Equatable, Sendable {
    /// Mode is not specified.
    case unspecified
    /// Deprecated: Use CLUSTER_DISABLED instead.
    @available(*, deprecated)
    case standalone
    /// Instance is in cluster mode.
    case cluster
    /// Cluster mode is disabled for the instance.
    case clusterDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standalone: return 1
      case .cluster: return 2
      case .clusterDisabled: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODE_UNSPECIFIED"
      case .standalone: return "STANDALONE"
      case .cluster: return "CLUSTER"
      case .clusterDisabled: return "CLUSTER_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Mode/unknownStringValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODE_UNSPECIFIED": self = .unspecified
      case "STANDALONE": self = .standalone
      case "CLUSTER": self = .cluster
      case "CLUSTER_DISABLED": self = .clusterDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Mode/unknownIntValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standalone
      case 2: self = .cluster
      case 4: self = .clusterDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("MODE_UNSPECIFIED")
      case .standalone: return try container.encode("STANDALONE")
      case .cluster: return try container.encode("CLUSTER")
      case .clusterDisabled: return try container.encode("CLUSTER_DISABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Server CA mode for the instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ServerCaMode: Codable, Equatable, Sendable {
    /// Server CA mode not specified.
    case unspecified
    /// Each instance has its own Google-managed CA.
    case googleManagedPerInstanceCa
    /// The instance uses a Google-managed shared CA for the instance's region.
    case googleManagedSharedCa
    /// The instance uses a customer-managed CA from CAS.
    case customerManagedCasCa
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .googleManagedPerInstanceCa: return 1
      case .googleManagedSharedCa: return 2
      case .customerManagedCasCa: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SERVER_CA_MODE_UNSPECIFIED"
      case .googleManagedPerInstanceCa: return "GOOGLE_MANAGED_PER_INSTANCE_CA"
      case .googleManagedSharedCa: return "GOOGLE_MANAGED_SHARED_CA"
      case .customerManagedCasCa: return "CUSTOMER_MANAGED_CAS_CA"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ServerCaMode/unknownStringValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SERVER_CA_MODE_UNSPECIFIED": self = .unspecified
      case "GOOGLE_MANAGED_PER_INSTANCE_CA": self = .googleManagedPerInstanceCa
      case "GOOGLE_MANAGED_SHARED_CA": self = .googleManagedSharedCa
      case "CUSTOMER_MANAGED_CAS_CA": self = .customerManagedCasCa
      case "SERVER_CA_MODE_GOOGLE_MANAGED_PER_INSTANCE_CA": self = .googleManagedPerInstanceCa
      case "SERVER_CA_MODE_GOOGLE_MANAGED_SHARED_CA": self = .googleManagedSharedCa
      case "SERVER_CA_MODE_CUSTOMER_MANAGED_CAS_CA": self = .customerManagedCasCa
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ServerCaMode/unknownIntValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .googleManagedPerInstanceCa
      case 2: self = .googleManagedSharedCa
      case 3: self = .customerManagedCasCa
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SERVER_CA_MODE_UNSPECIFIED")
      case .googleManagedPerInstanceCa:
        return try container.encode("GOOGLE_MANAGED_PER_INSTANCE_CA")
      case .googleManagedSharedCa: return try container.encode("GOOGLE_MANAGED_SHARED_CA")
      case .customerManagedCasCa: return try container.encode("CUSTOMER_MANAGED_CAS_CA")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The source to import from.
  public enum OneOf_ImportSources: Codable, Equatable, Sendable {
    /// Optional. Immutable. Backups that stored in Cloud Storage buckets.
    /// The Cloud Storage buckets need to be the same region as the instances.
    /// Read permission is required to import from the provided Cloud Storage
    /// Objects.
    indirect case gcsSource(Instance.GcsBackupSource?)
    /// Optional. Immutable. Backups that generated and managed by memorystore
    /// service.
    indirect case managedBackupSource(Instance.ManagedBackupSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
