// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class MemorystoreRetry: MemorystoreStub {
    let inner: any MemorystoreStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any MemorystoreStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListInstancesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.Instance {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func getCertificateAuthority(
      request: GetCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.CertificateAuthority {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.CertificateAuthority
          in
          return try await self.inner.getCertificateAuthority(request: r, options: o)
        })
    }

    public func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSharedRegionalCertificateAuthorityRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority
          in
          return try await self.inner.getSharedRegionalCertificateAuthority(request: r, options: o)
        })
    }

    public func rescheduleMaintenance(
      request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RescheduleMaintenanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.rescheduleMaintenance(request: r, options: o)
        })
    }

    public func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupCollectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse
          in
          return try await self.inner.listBackupCollections(request: r, options: o)
        })
    }

    public func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.BackupCollection {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupCollectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.BackupCollection
          in
          return try await self.inner.getBackupCollection(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListBackupsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.Backup {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func exportBackup(
      request: ExportBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportBackup(request: r, options: o)
        })
    }

    public func backupInstance(
      request: BackupInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BackupInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.backupInstance(request: r, options: o)
        })
    }

    public func startMigration(
      request: StartMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startMigration(request: r, options: o)
        })
    }

    public func finishMigration(
      request: FinishMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FinishMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.finishMigration(request: r, options: o)
        })
    }

    public func listTokenAuthUsers(
      request: ListTokenAuthUsersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTokenAuthUsersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse
          in
          return try await self.inner.listTokenAuthUsers(request: r, options: o)
        })
    }

    public func getTokenAuthUser(
      request: GetTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.TokenAuthUser {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTokenAuthUserRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.TokenAuthUser
          in
          return try await self.inner.getTokenAuthUser(request: r, options: o)
        })
    }

    public func listAuthTokens(
      request: ListAuthTokensRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAuthTokensRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse
          in
          return try await self.inner.listAuthTokens(request: r, options: o)
        })
    }

    public func getAuthToken(
      request: GetAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.AuthToken {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAuthTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMemoryStoreV1.AuthToken
          in
          return try await self.inner.getAuthToken(request: r, options: o)
        })
    }

    public func addTokenAuthUser(
      request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AddTokenAuthUserRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.addTokenAuthUser(request: r, options: o)
        })
    }

    public func deleteTokenAuthUser(
      request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTokenAuthUserRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTokenAuthUser(request: r, options: o)
        })
    }

    public func addAuthToken(
      request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AddAuthTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.addAuthToken(request: r, options: o)
        })
    }

    public func deleteAuthToken(
      request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAuthTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAuthToken(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
