// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "MemorystoreQuickstart")
public final class MemorystoreClient: Clients.MemorystoreProtocol, Sendable {
  let inner: any Clients.MemorystoreStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `MemorystoreClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.MemorystoreStub = try Clients.MemorystoreTransport(options)
    inner = Clients.MemorystoreRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MemorystoreLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets details of a single Instance.
  ///
  /// @Snippet(path: "Memorystore_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates a new Instance in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates a new Instance in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_CreateInstance")
  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.createInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Instance.
  ///
  /// @Snippet(path: "Memorystore_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Updates the parameters of a single Instance.
  ///
  /// @Snippet(path: "Memorystore_UpdateInstance")
  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.updateInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes a single Instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteInstance")
  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details about the certificate authority for an Instance.
  ///
  /// @Snippet(path: "Memorystore_GetCertificateAuthority")
  public func getCertificateAuthority(
    request: GetCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.CertificateAuthority {
    try await self.inner.getCertificateAuthority(request: request, options: options)
  }

  /// Gets the details of shared regional certificate authority information for
  /// Memorystore instance.
  ///
  /// @Snippet(path: "Memorystore_GetSharedRegionalCertificateAuthority")
  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority {
    try await self.inner.getSharedRegionalCertificateAuthority(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "Memorystore_RescheduleMaintenance")
  public func rescheduleMaintenance(
    request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rescheduleMaintenance(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "Memorystore_RescheduleMaintenance")
  public func rescheduleMaintenancePollingUntilDone(
    request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.rescheduleMaintenance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "Memorystore_ListBackupCollections")
  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse {
    try await self.inner.listBackupCollections(request: request, options: options)
  }

  /// Get a backup collection.
  ///
  /// @Snippet(path: "Memorystore_GetBackupCollection")
  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.BackupCollection {
    try await self.inner.getBackupCollection(request: request, options: options)
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "Memorystore_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Gets the details of a specific backup.
  ///
  /// @Snippet(path: "Memorystore_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "Memorystore_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "Memorystore_DeleteBackup")
  public func deleteBackupPollingUntilDone(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "Memorystore_ExportBackup")
  public func exportBackup(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportBackup(request: request, options: options)
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "Memorystore_ExportBackup")
  public func exportBackupPollingUntilDone(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.exportBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Backup Instance.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the instance's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "Memorystore_BackupInstance")
  public func backupInstance(
    request: BackupInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.backupInstance(request: request, options: options)
  }

  /// Backup Instance.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the instance's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "Memorystore_BackupInstance")
  public func backupInstancePollingUntilDone(
    request: BackupInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.backupInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Initiates the migration of a source instance to the target Memorystore
  /// instance.
  ///
  /// After the successful completion of this operation, the target instance
  /// will:
  /// 1. Set up replication with the source instance and replicate any writes to
  /// the source instance.
  /// 2. Only allow reads.
  ///
  /// @Snippet(path: "Memorystore_StartMigration")
  public func startMigration(
    request: StartMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startMigration(request: request, options: options)
  }

  /// Initiates the migration of a source instance to the target Memorystore
  /// instance.
  ///
  /// After the successful completion of this operation, the target instance
  /// will:
  /// 1. Set up replication with the source instance and replicate any writes to
  /// the source instance.
  /// 2. Only allow reads.
  ///
  /// @Snippet(path: "Memorystore_StartMigration")
  public func startMigrationPollingUntilDone(
    request: StartMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.startMigration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Finalizes the migration process.
  ///
  /// After the successful completion of this operation, the target instance
  /// will:
  /// 1. Stop replicating from the source instance.
  /// 2. Allow both reads and writes.
  ///
  /// @Snippet(path: "Memorystore_FinishMigration")
  public func finishMigration(
    request: FinishMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.finishMigration(request: request, options: options)
  }

  /// Finalizes the migration process.
  ///
  /// After the successful completion of this operation, the target instance
  /// will:
  /// 1. Stop replicating from the source instance.
  /// 2. Allow both reads and writes.
  ///
  /// @Snippet(path: "Memorystore_FinishMigration")
  public func finishMigrationPollingUntilDone(
    request: FinishMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.finishMigration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all the token auth users for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_ListTokenAuthUsers")
  public func listTokenAuthUsers(
    request: ListTokenAuthUsersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse {
    try await self.inner.listTokenAuthUsers(request: request, options: options)
  }

  /// Gets a specific token auth user for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_GetTokenAuthUser")
  public func getTokenAuthUser(
    request: GetTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.TokenAuthUser {
    try await self.inner.getTokenAuthUser(request: request, options: options)
  }

  /// Lists all the auth tokens for a specific token auth user.
  ///
  /// @Snippet(path: "Memorystore_ListAuthTokens")
  public func listAuthTokens(
    request: ListAuthTokensRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse {
    try await self.inner.listAuthTokens(request: request, options: options)
  }

  /// Gets a token based auth enabled instance's auth token for a given user.
  ///
  /// @Snippet(path: "Memorystore_GetAuthToken")
  public func getAuthToken(
    request: GetAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.AuthToken {
    try await self.inner.getAuthToken(request: request, options: options)
  }

  /// Adds a token auth user for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_AddTokenAuthUser")
  public func addTokenAuthUser(
    request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.addTokenAuthUser(request: request, options: options)
  }

  /// Adds a token auth user for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_AddTokenAuthUser")
  public func addTokenAuthUserPollingUntilDone(
    request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.addTokenAuthUser(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a token auth user for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteTokenAuthUser")
  public func deleteTokenAuthUser(
    request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteTokenAuthUser(request: request, options: options)
  }

  /// Deletes a token auth user for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteTokenAuthUser")
  public func deleteTokenAuthUserPollingUntilDone(
    request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteTokenAuthUser(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Adds a token for a user of a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_AddAuthToken")
  public func addAuthToken(
    request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.addAuthToken(request: request, options: options)
  }

  /// Adds a token for a user of a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_AddAuthToken")
  public func addAuthTokenPollingUntilDone(
    request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<TokenAuthUser> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<TokenAuthUser>.State in
      return try op._extractStatus(TokenAuthUser.self)
    }
    let rawOp = try await self.addAuthToken(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<TokenAuthUser>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a token for a user of a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteAuthToken")
  public func deleteAuthToken(
    request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAuthToken(request: request, options: options)
  }

  /// Deletes a token for a user of a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteAuthToken")
  public func deleteAuthTokenPollingUntilDone(
    request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAuthToken(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Memorystore_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Memorystore_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Memorystore_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Memorystore_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Memorystore_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Memorystore_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MemorystoreClient`.
  ///
  /// To mock `MemorystoreClient` change your functions to receive
  /// `some MemorystoreProtocol` or `any MemorystoreProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MemorystoreProtocol: Sendable {
    /// See `MemorystoreClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListInstancesResponse

    /// See `MemorystoreClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.Instance

    /// See `MemorystoreClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.createInstance`.
    func createInstancePollingUntilDone(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.updateInstance`.
    func updateInstancePollingUntilDone(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `MemorystoreClient.getCertificateAuthority`.
    func getCertificateAuthority(
      request: GetCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.CertificateAuthority

    /// See `MemorystoreClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenance(
      request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenancePollingUntilDone(
      request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.listBackupCollections`.
    func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse

    /// See `MemorystoreClient.getBackupCollection`.
    func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.BackupCollection

    /// See `MemorystoreClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListBackupsResponse

    /// See `MemorystoreClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.Backup

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackupPollingUntilDone(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `MemorystoreClient.exportBackup`.
    func exportBackup(
      request: ExportBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.exportBackup`.
    func exportBackupPollingUntilDone(
      request: ExportBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `MemorystoreClient.backupInstance`.
    func backupInstance(
      request: BackupInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.backupInstance`.
    func backupInstancePollingUntilDone(
      request: BackupInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.startMigration`.
    func startMigration(
      request: StartMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.startMigration`.
    func startMigrationPollingUntilDone(
      request: StartMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.finishMigration`.
    func finishMigration(
      request: FinishMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.finishMigration`.
    func finishMigrationPollingUntilDone(
      request: FinishMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.listTokenAuthUsers`.
    func listTokenAuthUsers(
      request: ListTokenAuthUsersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse

    /// See `MemorystoreClient.getTokenAuthUser`.
    func getTokenAuthUser(
      request: GetTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.TokenAuthUser

    /// See `MemorystoreClient.listAuthTokens`.
    func listAuthTokens(
      request: ListAuthTokensRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse

    /// See `MemorystoreClient.getAuthToken`.
    func getAuthToken(
      request: GetAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.AuthToken

    /// See `MemorystoreClient.addTokenAuthUser`.
    func addTokenAuthUser(
      request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.addTokenAuthUser`.
    func addTokenAuthUserPollingUntilDone(
      request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `MemorystoreClient.deleteTokenAuthUser`.
    func deleteTokenAuthUser(
      request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.deleteTokenAuthUser`.
    func deleteTokenAuthUserPollingUntilDone(
      request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `MemorystoreClient.addAuthToken`.
    func addAuthToken(
      request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.addAuthToken`.
    func addAuthTokenPollingUntilDone(
      request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<TokenAuthUser>

    /// See `MemorystoreClient.deleteAuthToken`.
    func deleteAuthToken(
      request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MemorystoreClient.deleteAuthToken`.
    func deleteAuthTokenPollingUntilDone(
      request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `MemorystoreClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `MemorystoreClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `MemorystoreClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `MemorystoreClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `MemorystoreClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.MemorystoreProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudMemoryStoreV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstancesByItems(
    request: ListInstancesRequest
  ) -> some AsyncSequence<Instance, Swift.Error> & Sendable {
    self.listInstancesByItems(request: request, options: .init())
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_ListInstances")
  public func listInstancesByItems(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Instance, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudMemoryStoreV1.ListInstancesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstancesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Instance, Swift.Error> & Sendable {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return self.listInstancesByItems(request: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudMemoryStoreV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.createInstancePollingUntilDone(request: request, options: .init())
  }

  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstancePollingUntilDone(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstancePollingUntilDone(request: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.updateInstancePollingUntilDone(request: request, options: .init())
  }

  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstancePollingUntilDone(
    instance: Instance?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstancePollingUntilDone(request: request)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInstancePollingUntilDone(request: request, options: .init())
  }

  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstancePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstancePollingUntilDone(request: request)
  }

  public func getCertificateAuthority(request: GetCertificateAuthorityRequest) async throws
    -> GoogleCloudMemoryStoreV1.CertificateAuthority
  {
    try await self.getCertificateAuthority(request: request, options: .init())
  }

  public func getCertificateAuthority(
    request: GetCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.CertificateAuthority {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.CertificateAuthority {
    let request = GetCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getCertificateAuthority(request: request)
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest
  ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority {
    try await self.getSharedRegionalCertificateAuthority(request: request, options: .init())
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSharedRegionalCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority {
    let request = GetSharedRegionalCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getSharedRegionalCertificateAuthority(request: request)
  }

  public func rescheduleMaintenance(request: RescheduleMaintenanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.rescheduleMaintenance(request: request, options: .init())
  }

  public func rescheduleMaintenance(
    request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func rescheduleMaintenancePollingUntilDone(request: RescheduleMaintenanceRequest)
    async throws -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.rescheduleMaintenancePollingUntilDone(request: request, options: .init())
  }

  public func rescheduleMaintenancePollingUntilDone(
    request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rescheduleMaintenancePollingUntilDone(
    name: Swift.String,
    rescheduleType: RescheduleMaintenanceRequest.RescheduleType,
    scheduleTime: GoogleWKT.WKTTimestamp?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = RescheduleMaintenanceRequest().with {
      $0.name = name
      $0.rescheduleType = rescheduleType
      $0.scheduleTime = scheduleTime
    }
    return try await self.rescheduleMaintenancePollingUntilDone(request: request)
  }

  public func listBackupCollections(request: ListBackupCollectionsRequest) async throws
    -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse
  {
    try await self.listBackupCollections(request: request, options: .init())
  }

  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBackupCollectionsByItems(
    request: ListBackupCollectionsRequest
  ) -> some AsyncSequence<BackupCollection, Swift.Error> & Sendable {
    self.listBackupCollectionsByItems(request: request, options: .init())
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "Memorystore_ListBackupCollections")
  public func listBackupCollectionsByItems(
    request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<BackupCollection, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listBackupCollections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupCollectionsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<BackupCollection, Swift.Error> & Sendable {
    let request = ListBackupCollectionsRequest().with {
      $0.parent = parent
    }
    return self.listBackupCollectionsByItems(request: request)
  }

  public func getBackupCollection(request: GetBackupCollectionRequest) async throws
    -> GoogleCloudMemoryStoreV1.BackupCollection
  {
    try await self.getBackupCollection(request: request, options: .init())
  }

  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.BackupCollection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBackupCollection(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.BackupCollection {
    let request = GetBackupCollectionRequest().with {
      $0.name = name
    }
    return try await self.getBackupCollection(request: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudMemoryStoreV1.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListBackupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBackupsByItems(
    request: ListBackupsRequest
  ) -> some AsyncSequence<Backup, Swift.Error> & Sendable {
    self.listBackupsByItems(request: request, options: .init())
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "Memorystore_ListBackups")
  public func listBackupsByItems(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Backup, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudMemoryStoreV1.ListBackupsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Backup, Swift.Error> & Sendable {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return self.listBackupsByItems(request: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudMemoryStoreV1.Backup {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.Backup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteBackupPollingUntilDone(request: DeleteBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteBackupPollingUntilDone(request: request, options: .init())
  }

  public func deleteBackupPollingUntilDone(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBackupPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    return try await self.deleteBackupPollingUntilDone(request: request)
  }

  public func exportBackup(request: ExportBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.exportBackup(request: request, options: .init())
  }

  public func exportBackup(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func exportBackupPollingUntilDone(request: ExportBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Backup>
  {
    try await self.exportBackupPollingUntilDone(request: request, options: .init())
  }

  public func exportBackupPollingUntilDone(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupInstance(request: BackupInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.backupInstance(request: request, options: .init())
  }

  public func backupInstance(
    request: BackupInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func backupInstancePollingUntilDone(request: BackupInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.backupInstancePollingUntilDone(request: request, options: .init())
  }

  public func backupInstancePollingUntilDone(
    request: BackupInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupInstancePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = BackupInstanceRequest().with {
      $0.name = name
    }
    return try await self.backupInstancePollingUntilDone(request: request)
  }

  public func startMigration(request: StartMigrationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.startMigration(request: request, options: .init())
  }

  public func startMigration(
    request: StartMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func startMigrationPollingUntilDone(request: StartMigrationRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.startMigrationPollingUntilDone(request: request, options: .init())
  }

  public func startMigrationPollingUntilDone(
    request: StartMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func finishMigration(request: FinishMigrationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.finishMigration(request: request, options: .init())
  }

  public func finishMigration(
    request: FinishMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func finishMigrationPollingUntilDone(request: FinishMigrationRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.finishMigrationPollingUntilDone(request: request, options: .init())
  }

  public func finishMigrationPollingUntilDone(
    request: FinishMigrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func finishMigrationPollingUntilDone(
    name: Swift.String,
    force: Swift.Bool,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = FinishMigrationRequest().with {
      $0.name = name
      $0.force = force
    }
    return try await self.finishMigrationPollingUntilDone(request: request)
  }

  public func listTokenAuthUsers(request: ListTokenAuthUsersRequest) async throws
    -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse
  {
    try await self.listTokenAuthUsers(request: request, options: .init())
  }

  public func listTokenAuthUsers(
    request: ListTokenAuthUsersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTokenAuthUsersByItems(
    request: ListTokenAuthUsersRequest
  ) -> some AsyncSequence<TokenAuthUser, Swift.Error> & Sendable {
    self.listTokenAuthUsersByItems(request: request, options: .init())
  }

  /// Lists all the token auth users for a token based auth enabled instance.
  ///
  /// @Snippet(path: "Memorystore_ListTokenAuthUsers")
  public func listTokenAuthUsersByItems(
    request: ListTokenAuthUsersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<TokenAuthUser, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse in
      var request = request
      request.pageToken = token
      return try await self.listTokenAuthUsers(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTokenAuthUsersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<TokenAuthUser, Swift.Error> & Sendable {
    let request = ListTokenAuthUsersRequest().with {
      $0.parent = parent
    }
    return self.listTokenAuthUsersByItems(request: request)
  }

  public func getTokenAuthUser(request: GetTokenAuthUserRequest) async throws
    -> GoogleCloudMemoryStoreV1.TokenAuthUser
  {
    try await self.getTokenAuthUser(request: request, options: .init())
  }

  public func getTokenAuthUser(
    request: GetTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.TokenAuthUser {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getTokenAuthUser(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.TokenAuthUser {
    let request = GetTokenAuthUserRequest().with {
      $0.name = name
    }
    return try await self.getTokenAuthUser(request: request)
  }

  public func listAuthTokens(request: ListAuthTokensRequest) async throws
    -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse
  {
    try await self.listAuthTokens(request: request, options: .init())
  }

  public func listAuthTokens(
    request: ListAuthTokensRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAuthTokensByItems(
    request: ListAuthTokensRequest
  ) -> some AsyncSequence<AuthToken, Swift.Error> & Sendable {
    self.listAuthTokensByItems(request: request, options: .init())
  }

  /// Lists all the auth tokens for a specific token auth user.
  ///
  /// @Snippet(path: "Memorystore_ListAuthTokens")
  public func listAuthTokensByItems(
    request: ListAuthTokensRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AuthToken, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse in
      var request = request
      request.pageToken = token
      return try await self.listAuthTokens(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAuthTokensByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AuthToken, Swift.Error> & Sendable {
    let request = ListAuthTokensRequest().with {
      $0.parent = parent
    }
    return self.listAuthTokensByItems(request: request)
  }

  public func getAuthToken(request: GetAuthTokenRequest) async throws
    -> GoogleCloudMemoryStoreV1.AuthToken
  {
    try await self.getAuthToken(request: request, options: .init())
  }

  public func getAuthToken(
    request: GetAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMemoryStoreV1.AuthToken {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAuthToken(
    name: Swift.String,
  ) async throws -> GoogleCloudMemoryStoreV1.AuthToken {
    let request = GetAuthTokenRequest().with {
      $0.name = name
    }
    return try await self.getAuthToken(request: request)
  }

  public func addTokenAuthUser(request: AddTokenAuthUserRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.addTokenAuthUser(request: request, options: .init())
  }

  public func addTokenAuthUser(
    request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func addTokenAuthUserPollingUntilDone(request: AddTokenAuthUserRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.addTokenAuthUserPollingUntilDone(request: request, options: .init())
  }

  public func addTokenAuthUserPollingUntilDone(
    request: AddTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func addTokenAuthUserPollingUntilDone(
    instance: Swift.String,
    tokenAuthUser: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = AddTokenAuthUserRequest().with {
      $0.instance = instance
      $0.tokenAuthUser = tokenAuthUser
    }
    return try await self.addTokenAuthUserPollingUntilDone(request: request)
  }

  public func deleteTokenAuthUser(request: DeleteTokenAuthUserRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteTokenAuthUser(request: request, options: .init())
  }

  public func deleteTokenAuthUser(
    request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteTokenAuthUserPollingUntilDone(request: DeleteTokenAuthUserRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteTokenAuthUserPollingUntilDone(request: request, options: .init())
  }

  public func deleteTokenAuthUserPollingUntilDone(
    request: DeleteTokenAuthUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteTokenAuthUserPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteTokenAuthUserRequest().with {
      $0.name = name
    }
    return try await self.deleteTokenAuthUserPollingUntilDone(request: request)
  }

  public func addAuthToken(request: AddAuthTokenRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.addAuthToken(request: request, options: .init())
  }

  public func addAuthToken(
    request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func addAuthTokenPollingUntilDone(request: AddAuthTokenRequest) async throws
    -> any GoogleGax.PollableOperation<TokenAuthUser>
  {
    try await self.addAuthTokenPollingUntilDone(request: request, options: .init())
  }

  public func addAuthTokenPollingUntilDone(
    request: AddAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<TokenAuthUser> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<TokenAuthUser>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func addAuthTokenPollingUntilDone(
    tokenAuthUser: Swift.String,
    authToken: AuthToken?,
  ) async throws -> any GoogleGax.PollableOperation<TokenAuthUser> {
    let request = AddAuthTokenRequest().with {
      $0.tokenAuthUser = tokenAuthUser
      $0.authToken = authToken
    }
    return try await self.addAuthTokenPollingUntilDone(request: request)
  }

  public func deleteAuthToken(request: DeleteAuthTokenRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAuthToken(request: request, options: .init())
  }

  public func deleteAuthToken(
    request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAuthTokenPollingUntilDone(request: DeleteAuthTokenRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAuthTokenPollingUntilDone(request: request, options: .init())
  }

  public func deleteAuthTokenPollingUntilDone(
    request: DeleteAuthTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAuthTokenPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAuthTokenRequest().with {
      $0.name = name
    }
    return try await self.deleteAuthTokenPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Memorystore_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Memorystore_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
