// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents persistence configuration for a instance.
public struct PersistenceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Current persistence mode.
  public var mode: PersistenceConfig.PersistenceMode = PersistenceConfig.PersistenceMode()

  /// Optional. RDB configuration. This field will be ignored if mode is not RDB.
  public var rdbConfig: PersistenceConfig.RDBConfig? = nil

  /// Optional. AOF configuration. This field will be ignored if mode is not AOF.
  public var aofConfig: PersistenceConfig.AOFConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PersistenceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PersistenceConfig().with { $0.mode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mode = CodingKeys(stringValue: "mode")
    static let rdbConfig = CodingKeys(stringValue: "rdbConfig")
    static let aofConfig = CodingKeys(stringValue: "aofConfig")

    static let _knownKeys: Set<Swift.String> = [
      "mode",
      "rdbConfig",
      "aofConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      PersistenceConfig.PersistenceMode.self, forKey: .mode)
    {
      self.mode = value
    }
    self.rdbConfig = try container.decodeIfPresent(
      PersistenceConfig.RDBConfig.self, forKey: .rdbConfig)
    self.aofConfig = try container.decodeIfPresent(
      PersistenceConfig.AOFConfig.self, forKey: .aofConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mode, forKey: .mode)
    try container.encodeIfPresent(self.rdbConfig, forKey: .rdbConfig)
    try container.encodeIfPresent(self.aofConfig, forKey: .aofConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for RDB based persistence.
  public struct RDBConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Period between RDB snapshots.
    public var rdbSnapshotPeriod: PersistenceConfig.RDBConfig.SnapshotPeriod = PersistenceConfig
      .RDBConfig.SnapshotPeriod()

    /// Optional. Time that the first snapshot was/will be attempted, and to
    /// which future snapshots will be aligned. If not provided, the current time
    /// will be used.
    public var rdbSnapshotStartTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RDBConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RDBConfig().with { $0.rdbSnapshotPeriod = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let rdbSnapshotPeriod = CodingKeys(stringValue: "rdbSnapshotPeriod")
      static let rdbSnapshotStartTime = CodingKeys(stringValue: "rdbSnapshotStartTime")

      static let _knownKeys: Set<Swift.String> = [
        "rdbSnapshotPeriod",
        "rdbSnapshotStartTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        PersistenceConfig.RDBConfig.SnapshotPeriod.self, forKey: .rdbSnapshotPeriod)
      {
        self.rdbSnapshotPeriod = value
      }
      self.rdbSnapshotStartTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .rdbSnapshotStartTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.rdbSnapshotPeriod, forKey: .rdbSnapshotPeriod)
      try container.encodeIfPresent(self.rdbSnapshotStartTime, forKey: .rdbSnapshotStartTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Possible snapshot periods.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SnapshotPeriod: Codable, Equatable, Sendable {
      /// Not set.
      case unspecified
      /// One hour.
      case oneHour
      /// Six hours.
      case sixHours
      /// Twelve hours.
      case twelveHours
      /// Twenty four hours.
      case twentyFourHours
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .oneHour: return 1
        case .sixHours: return 2
        case .twelveHours: return 3
        case .twentyFourHours: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SNAPSHOT_PERIOD_UNSPECIFIED"
        case .oneHour: return "ONE_HOUR"
        case .sixHours: return "SIX_HOURS"
        case .twelveHours: return "TWELVE_HOURS"
        case .twentyFourHours: return "TWENTY_FOUR_HOURS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SnapshotPeriod/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SNAPSHOT_PERIOD_UNSPECIFIED": self = .unspecified
        case "ONE_HOUR": self = .oneHour
        case "SIX_HOURS": self = .sixHours
        case "TWELVE_HOURS": self = .twelveHours
        case "TWENTY_FOUR_HOURS": self = .twentyFourHours
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SnapshotPeriod/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .oneHour
        case 2: self = .sixHours
        case 3: self = .twelveHours
        case 4: self = .twentyFourHours
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SNAPSHOT_PERIOD_UNSPECIFIED")
        case .oneHour: return try container.encode("ONE_HOUR")
        case .sixHours: return try container.encode("SIX_HOURS")
        case .twelveHours: return try container.encode("TWELVE_HOURS")
        case .twentyFourHours: return try container.encode("TWENTY_FOUR_HOURS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.PersistenceConfig.RDBConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for AOF based persistence.
  public struct AOFConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The fsync mode.
    public var appendFsync: PersistenceConfig.AOFConfig.AppendFsync = PersistenceConfig.AOFConfig
      .AppendFsync()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AOFConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AOFConfig().with { $0.appendFsync = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let appendFsync = CodingKeys(stringValue: "appendFsync")

      static let _knownKeys: Set<Swift.String> = [
        "appendFsync"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        PersistenceConfig.AOFConfig.AppendFsync.self, forKey: .appendFsync)
      {
        self.appendFsync = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.appendFsync, forKey: .appendFsync)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Possible fsync modes.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum AppendFsync: Codable, Equatable, Sendable {
      /// Not set. Default: EVERY_SEC
      case unspecified
      /// Never fsync. Normally Linux will flush data every 30 seconds with this
      /// configuration, but it's up to the kernel's exact tuning.
      case never
      /// Fsync every second. You may lose 1 second of data if there is a
      /// disaster.
      case everySec
      /// Fsync every time new write commands are appended to the AOF. The best
      /// data loss protection at the cost of performance.
      case always
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .never: return 1
        case .everySec: return 2
        case .always: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "APPEND_FSYNC_UNSPECIFIED"
        case .never: return "NEVER"
        case .everySec: return "EVERY_SEC"
        case .always: return "ALWAYS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AppendFsync/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "APPEND_FSYNC_UNSPECIFIED": self = .unspecified
        case "NEVER": self = .never
        case "EVERY_SEC": self = .everySec
        case "ALWAYS": self = .always
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AppendFsync/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .never
        case 2: self = .everySec
        case 3: self = .always
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("APPEND_FSYNC_UNSPECIFIED")
        case .never: return try container.encode("NEVER")
        case .everySec: return try container.encode("EVERY_SEC")
        case .always: return try container.encode("ALWAYS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memorystore.v1.PersistenceConfig.AOFConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible persistence modes.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PersistenceMode: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Persistence is disabled, and any snapshot data is deleted.
    case disabled
    /// RDB based persistence is enabled.
    case rdb
    /// AOF based persistence is enabled.
    case aof
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .disabled: return 1
      case .rdb: return 2
      case .aof: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERSISTENCE_MODE_UNSPECIFIED"
      case .disabled: return "DISABLED"
      case .rdb: return "RDB"
      case .aof: return "AOF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PersistenceMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERSISTENCE_MODE_UNSPECIFIED": self = .unspecified
      case "DISABLED": self = .disabled
      case "RDB": self = .rdb
      case "AOF": self = .aof
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PersistenceMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .disabled
      case 2: self = .rdb
      case 3: self = .aof
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PERSISTENCE_MODE_UNSPECIFIED")
      case .disabled: return try container.encode("DISABLED")
      case .rdb: return try container.encode("RDB")
      case .aof: return try container.encode("AOF")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.PersistenceConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
