// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// User created Psc connection configuration.
public struct PscConnection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The PSC connection id of the forwarding rule connected to the
  /// service attachment.
  public var pscConnectionId: Swift.String = Swift.String()

  /// Required. The IP allocated on the consumer network for the PSC forwarding
  /// rule.
  public var ipAddress: Swift.String = Swift.String()

  /// Required. The URI of the consumer side forwarding rule.
  /// Format:
  /// projects/{project}/regions/{region}/forwardingRules/{forwarding_rule}
  public var forwardingRule: Swift.String = Swift.String()

  /// Output only. The consumer project_id where the forwarding rule is created
  /// from.
  public var projectId: Swift.String = Swift.String()

  /// Required. The consumer network where the IP address resides, in the form of
  /// projects/{project_id}/global/networks/{network_name}.
  public var network: Swift.String = Swift.String()

  /// Required. The service attachment which is the target of the PSC connection,
  /// in the form of
  /// projects/{project-id}/regions/{region}/serviceAttachments/{service-attachment-id}.
  public var serviceAttachment: Swift.String = Swift.String()

  /// Output only. The status of the PSC connection: whether a connection exists
  /// and ACTIVE or it no longer exists. Please note that this value is updated
  /// periodically. Please use Private Service Connect APIs for the latest
  /// status.
  public var pscConnectionStatus: PscConnectionStatus = PscConnectionStatus()

  /// Output only. Type of the PSC connection.
  public var connectionType: ConnectionType = ConnectionType()

  /// Ports of the exposed endpoint.
  public var ports: PortsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PscConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PscConnection().with { $0.port = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let port = CodingKeys(stringValue: "port")
    static let pscConnectionId = CodingKeys(stringValue: "pscConnectionId")
    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let forwardingRule = CodingKeys(stringValue: "forwardingRule")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let network = CodingKeys(stringValue: "network")
    static let serviceAttachment = CodingKeys(stringValue: "serviceAttachment")
    static let pscConnectionStatus = CodingKeys(stringValue: "pscConnectionStatus")
    static let connectionType = CodingKeys(stringValue: "connectionType")

    static let _knownKeys: Set<Swift.String> = [
      "port",
      "pscConnectionId",
      "ipAddress",
      "forwardingRule",
      "projectId",
      "network",
      "serviceAttachment",
      "pscConnectionStatus",
      "connectionType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pscConnectionId) {
      self.pscConnectionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .forwardingRule) {
      self.forwardingRule = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAttachment) {
      self.serviceAttachment = value
    }
    if let value = try container.decodeIfPresent(
      PscConnectionStatus.self, forKey: .pscConnectionStatus)
    {
      self.pscConnectionStatus = value
    }
    if let value = try container.decodeIfPresent(ConnectionType.self, forKey: .connectionType) {
      self.connectionType = value
    }

    var ports: PortsOneOf? = nil
    let portsCheckAndSet = {
      if ports != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'ports'"))
      }
      ports = $0
    }
    if let port = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      try portsCheckAndSet(.port(port))
    }
    self.ports = ports
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pscConnectionId, forKey: .pscConnectionId)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.forwardingRule, forKey: .forwardingRule)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.serviceAttachment, forKey: .serviceAttachment)
    try container.encode(self.pscConnectionStatus, forKey: .pscConnectionStatus)
    try container.encode(self.connectionType, forKey: .connectionType)

    if let choice = self.ports {
      switch choice {
      case .port(let value):
        try container.encode(value, forKey: .port)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Ports of the exposed endpoint.
  public enum PortsOneOf: Codable, Equatable, Sendable {
    /// Optional. port will only be set for Primary/Reader or Discovery endpoint.
    case port(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.PscConnection"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
