// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details of the self-managed source instance.
public struct SelfManagedSource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The IP address of the source instance.
  /// This IP address should be a stable IP address that can be accessed by the
  /// Memorystore instance throughout the migration process.
  public var ipAddress: Swift.String = Swift.String()

  /// Required. The port of the source instance.
  /// This port should be a stable port that can be accessed by the Memorystore
  /// instance throughout the migration process.
  public var port: Swift.Int32 = Swift.Int32()

  /// Required. The resource name of the Private Service Connect Network
  /// Attachment used to establish connectivity to the source instance. This
  /// network attachment has the following requirements:
  /// 1. It must be in the same project as the Memorystore instance.
  /// 2. It must be in the same region as the Memorystore instance.
  /// 3. The subnet attached to the network attachment must be in the same VPC
  /// network as the source instance nodes.
  ///
  /// Format:
  /// projects/{project}/regions/{region}/networkAttachments/{network_attachment}
  public var networkAttachment: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SelfManagedSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SelfManagedSource().with { $0.ipAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let port = CodingKeys(stringValue: "port")
    static let networkAttachment = CodingKeys(stringValue: "networkAttachment")

    static let _knownKeys: Set<Swift.String> = [
      "ipAddress",
      "port",
      "networkAttachment",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkAttachment) {
      self.networkAttachment = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.port, forKey: .port)
    try container.encode(self.networkAttachment, forKey: .networkAttachment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.SelfManagedSource"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
