// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Shared regional certificate authority for an instance.
public struct SharedRegionalCertificateAuthority: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Unique name of the resource in this scope including project and
  /// location using the form:
  ///     `projects/{project}/locations/{location}/sharedRegionalCertificateAuthority`
  public var name: Swift.String = Swift.String()

  /// Server ca information.
  public var serverCa: OneOf_ServerCa? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SharedRegionalCertificateAuthority`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SharedRegionalCertificateAuthority().with { $0.managedServerCa = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let managedServerCa = CodingKeys(stringValue: "managedServerCa")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "managedServerCa",
      "name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var serverCa: OneOf_ServerCa? = nil
    let serverCaCheckAndSet = {
      if serverCa != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'serverCa'"))
      }
      serverCa = $0
    }
    if let managedServerCa = try container.decodeIfPresent(
      SharedRegionalCertificateAuthority.RegionalManagedCertificateAuthority?.self,
      forKey: .managedServerCa)
    {
      try serverCaCheckAndSet(.managedServerCa(managedServerCa))
    }
    self.serverCa = serverCa
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.serverCa {
      switch choice {
      case .managedServerCa(let value):
        try container.encode(value, forKey: .managedServerCa)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// CA certificate chains for memorystore managed server authentication.
  public struct RegionalManagedCertificateAuthority: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The PEM encoded CA certificate chains for memorystore managed
    /// server authentication
    public var caCerts:
      [SharedRegionalCertificateAuthority.RegionalManagedCertificateAuthority.RegionalCertChain] =
        []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RegionalManagedCertificateAuthority`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RegionalManagedCertificateAuthority().with { $0.caCerts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let caCerts = CodingKeys(stringValue: "caCerts")

      static let _knownKeys: Set<Swift.String> = [
        "caCerts"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [SharedRegionalCertificateAuthority.RegionalManagedCertificateAuthority.RegionalCertChain]
          .self, forKey: .caCerts)
      {
        self.caCerts = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.caCerts, forKey: .caCerts)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The certificates that form the CA chain, from leaf to root order.
    public struct RegionalCertChain: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The certificates that form the CA chain, from leaf to root order.
      public var certificates: [Swift.String] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `RegionalCertChain`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RegionalCertChain().with { $0.certificates = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let certificates = CodingKeys(stringValue: "certificates")

        static let _knownKeys: Set<Swift.String> = [
          "certificates"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .certificates) {
          self.certificates = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.certificates, forKey: .certificates)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.memorystore.v1.SharedRegionalCertificateAuthority.RegionalManagedCertificateAuthority.RegionalCertChain"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.memorystore.v1.SharedRegionalCertificateAuthority.RegionalManagedCertificateAuthority"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Server ca information.
  public enum OneOf_ServerCa: Codable, Equatable, Sendable {
    /// CA certificate chains for memorystore managed server authentication.
    indirect case managedServerCa(
      SharedRegionalCertificateAuthority.RegionalManagedCertificateAuthority?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.SharedRegionalCertificateAuthority"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
